spring.application.name=appointment-service

server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/appointment_db
spring.datasource.username=postgres
spring.datasource.password=kimquan1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Circuit Breaker Config
resilience4j.circuitbreaker.instances.doctorServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.doctorServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.doctorServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.doctorServiceCB.permitted-number-of-calls-in-half-open-state=3

# B?t Log ?? xem tr?ng thái m?ch chuy?n ??i
logging.level.io.github.resilience4j=DEBUG

# C?u hình Retry cho instance mang tên 'patientRetry'
resilience4j.retry.instances.patientRetry.max-attempts=3
resilience4j.retry.instances.patientRetry.wait-duration=2s
# Ch? th? l?i khi không th? k?t n?i t?i server (ví d? m?ng s?p, server ch?a k?p kh?i ??ng)
resilience4j.retry.instances.patientRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException

# B?t log ?? theo dõi các l?n th? l?i trong Console
logging.level.io.github.resilience4j.retry=DEBUG

# C?u hình th?i gian ch? t?i ?a 1s
resilience4j.timelimiter.instances.insuranceTimeout.timeout-duration=1s
# (Tùy ch?n) In log ?? theo dõi
logging.level.io.github.resilience4j.timelimiter=DEBUG
