spring.application.name=configserver

server.port=8888

# ???ng d?n chu?n cho Windows
spring.cloud.config.server.git.uri=file:///C:/Users/admin/Desktop/md4/md4_ss9/pharmacy-config-repo
spring.cloud.config.server.git.default-label=master
