spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacy_db
app.branch-name=Nha Thuoc So 1
app.hotline=19001234

# Ng??ng l?i 50%
resilience4j.circuitbreaker.instances.warehouseCB.failure-rate-threshold=50
# S? cu?c g?i t?i thi?u ?? tính toán t? l? l?i
resilience4j.circuitbreaker.instances.warehouseCB.minimum-number-of-calls=5
# Th?i gian m?ch m? (OPEN) là 20 giây tr??c khi th? l?i
resilience4j.circuitbreaker.instances.warehouseCB.wait-duration-in-open-state=20s
# S? cu?c g?i th? nghi?m ? tr?ng thái HALF-OPEN
resilience4j.circuitbreaker.instances.warehouseCB.permitted-number-of-calls-in-half-open-state=3

# C?u hình Retry (T? ??ng th? l?i)
resilience4j.retry.instances.invoiceRetry.max-attempts=3
resilience4j.retry.instances.invoiceRetry.wait-duration=2s
resilience4j.retry.instances.invoiceRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException

#C?u hình Rate Limiter (Gi?i h?n t?n su?t)
resilience4j.ratelimiter.instances.invoiceLimit.limit-for-period=5
resilience4j.ratelimiter.instances.invoiceLimit.limit-refresh-period=10s
resilience4j.ratelimiter.instances.invoiceLimit.timeout-duration=0

# Log ?? theo dõi
logging.level.io.github.resilience4j=DEBUG

# TimeLimiter: Gi?i h?n 3 giây
resilience4j.timelimiter.instances.insuranceTL.timeout-duration=3s

# Retry: Th? l?i 3 l?n, m?i l?n cách nhau 2s
resilience4j.retry.instances.insuranceRetry.max-attempts=3
resilience4j.retry.instances.insuranceRetry.wait-duration=2s
resilience4j.retry.instances.insuranceRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException

# Circuit Breaker: Ng??ng l?i 60%
resilience4j.circuitbreaker.instances.insuranceCB.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.insuranceCB.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.insuranceCB.wait-duration-in-open-state=30s

# M? khóa Actuator ?? refresh c?u hình t? xa
management.endpoints.web.exposure.include=refresh